{# FROM #}
FROM {{ baseFrom }}
{# MAINTAINER #}
MAINTAINER {{ maintainer }}
{# RUN mkdir #}
{% if mkdirList != [] %}
{% for mkdir in mkdirList %}
{{ mkdir }}
{% endfor %}
{% endif %}

{# WORKDIR #}
WORKDIR {{ workdir }}
{# ENV #}
{% if envList is not none %}
{% for env in envList %}
ENV {{ env }}
{% endfor %}
{% endif %}
{# ADD #}
{% if addList is not none %}
{% for add in addList %}
ADD {{ add }}
{% endfor %}
{% endif %}
{# COPY #}
{% if copyList is not none %}
{% for copy in copyList %}
COPY {{ copy }}
{% endfor %}
{% endif %}

{# RUN #}
{% if runList != [] %}
{% for run in runList %}
{{ run }}
{% endfor %}
{% endif %}
{# EXPOSE #}
{% if expose %}
EXPOSE {{ expose }}
{% endif %}
{# USER #}
{#RUN groupadd -g 2002 container#}
{#RUN useradd -u 2002 -g container -d /home container#}
{#RUN chown -R container:container /home#}
{#RUN chmod -R 777 /home#}
{#USER container#}

{# ENTRYPOINT #}
{% if entrypoint %}
ENTRYPOINT {{ entrypoint }}
{% endif %}